# Generated by Django 4.0.2 on 2023-01-15 13:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('menus', '0002_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_address1_english', wagtail.core.fields.RichTextField(blank=True, max_length=255, null=True)),
                ('main_address1_arabic', wagtail.core.fields.RichTextField(blank=True, max_length=255, null=True)),
                ('address2_english', wagtail.core.fields.RichTextField(blank=True, max_length=255, null=True)),
                ('address2_arabic', wagtail.core.fields.RichTextField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(help_text='add school email', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=150)),
                ('footer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_item', to='menus.footer')),
                ('link_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
