# Generated by Django 4.0.2 on 2023-01-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_footer_schoolsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='address2_arabic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='address2_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='main_address1_arabic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='main_address1_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
