# Generated by Django 4.0.2 on 2023-01-16 06:53

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_footer_address2_arabic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='items',
            field=wagtail.core.fields.StreamField([('header_items', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255, required=True)), ('internal_url', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='If the internal_url above is selected there is no need to fill this field', required=False)), ('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=50, required=True)), ('internal_url', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='If the internal_url above is selected there is no need to fill this field', required=False))])))]))], blank=True, null=True),
        ),
    ]
