# Generated by Django 4.0.2 on 2023-01-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('page_with_side', '0002_vansection_rename_pagewithside_admissionpage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VanSection',
            new_name='NavSection',
        ),
    ]
