# Generated by Django 4.0.2 on 2023-01-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_with_side', '0003_rename_vansection_navsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navsection',
            name='nav_icon',
        ),
    ]
