# Generated by Django 4.0.2 on 2023-01-15 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_header'),
        ('home', '0008_homepage_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu', to='menus.header'),
        ),
    ]
