# Generated by Django 4.0.2 on 2023-01-15 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_footer_schoolsitem'),
        ('home', '0009_alter_homepage_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer', to='menus.footer'),
        ),
    ]
